name: Native-ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Terraform Cloud Workspace Init
        run: |
          curl -X POST https://api.github.com/repos/dashaun/terraform-cloud/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "init '"$GITHUB_REPOSITORY"'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: dynamic-tf-oci-arm64-runner
        run: |
          curl -X POST https://api.github.com/repos/dashaun/dynamic-tf-oci-arm64-runner/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "init '"$GITHUB_REPOSITORY"'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

  build:
    runs-on: ARM64
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: true
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative-arm64 spring-boot:build-image -DskipTests
